from __future__ import annotations

from pathlib import Path
from typing import Any

import cv2
import numpy as np
import pytesseract
from PIL import Image
from app.services.pdf_images import load_pdf_page_image


def _load_image(file_path: str) -> np.ndarray | None:
    try:
        path = Path(file_path)
        if path.suffix.lower() == ".pdf":
            return load_pdf_page_image(path, 0)
        data = np.fromfile(str(path), dtype=np.uint8)
        image = cv2.imdecode(data, cv2.IMREAD_COLOR)
        return image
    except Exception:
        return None


def _token_geometry_from_ocr(ocr_text: str, ocr_confidence: float) -> dict[str, float]:
    tokens = [t for t in str(ocr_text or "").split() if t.strip()]
    return {
        "token_count": float(len(tokens)),
        "mean_height": 0.0,
        "height_cv": 0.0,
        "mean_conf": float(ocr_confidence or 0.0),
        "conf_std": 0.0,
    }


def _block_texture(image: np.ndarray) -> dict[str, float]:
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape[:2]
    values = []
    noise_values = []
    for r in range(8):
        for c in range(8):
            y0, y1 = int(r * h / 8), int((r + 1) * h / 8)
            x0, x1 = int(c * w / 8), int((c + 1) * w / 8)
            block = gray[y0:y1, x0:x1]
            if block.size == 0:
                continue
            values.append(float(np.log1p(cv2.Laplacian(block, cv2.CV_64F).var())))
            blur = cv2.GaussianBlur(block, (3, 3), 0)
            residual = cv2.subtract(block, blur)
            noise_values.append(float(np.var(residual)))
    if not values:
        return {"texture_cv": 0.0, "noise_cv": 0.0, "texture_outlier_ratio": 0.0}
    arr = np.asarray(values, dtype=np.float64)
    noise = np.asarray(noise_values, dtype=np.float64)
    med = np.median(arr)
    mad = max(1.4826 * np.median(np.abs(arr - med)), 0.12)
    z = np.abs(arr - med) / mad
    return {
        "texture_cv": float(np.std(arr) / max(np.mean(np.abs(arr)), 0.1)),
        "noise_cv": float(np.std(noise) / max(np.mean(np.abs(noise)), 0.1)),
        "texture_outlier_ratio": float(np.mean(z >= 3.5)),
    }


def _ela_signal(file_path: str) -> dict[str, float]:
    try:
        original = Image.open(file_path).convert("RGB")
        from io import BytesIO
        buffer = BytesIO()
        original.save(buffer, format="JPEG", quality=90)
        buffer.seek(0)
        recompressed = Image.open(buffer).convert("RGB")
        a = np.asarray(original, dtype=np.float32)
        b = np.asarray(recompressed, dtype=np.float32)
        diff = np.mean(np.abs(a - b), axis=2)
        h, w = diff.shape
        blocks = []
        for r in range(8):
            for c in range(8):
                y0, y1 = int(r * h / 8), int((r + 1) * h / 8)
                x0, x1 = int(c * w / 8), int((c + 1) * w / 8)
                block = diff[y0:y1, x0:x1]
                if block.size:
                    blocks.append(float(np.mean(block)))
        if len(blocks) < 16:
            return {"ela_outlier_ratio": 0.0, "ela_max_z": 0.0}
        arr = np.asarray(blocks, dtype=np.float64)
        med = np.median(arr)
        mad = max(1.4826 * np.median(np.abs(arr - med)), 0.1)
        z = np.abs(arr - med) / mad
        return {"ela_outlier_ratio": float(np.mean(z >= 4.0)), "ela_max_z": float(np.max(z))}
    except Exception:
        return {"ela_outlier_ratio": 0.0, "ela_max_z": 0.0}


def analyze_ai_document(file_path: str, id_type: str, ocr_confidence: float, ocr_text: str, extracted_fields: dict[str, Any]) -> dict[str, Any]:
    result = {
        "enabled": False,
        "available": False,
        "band": "UNAVAILABLE",
        "score": 0.0,
        "aiCreatedRisk": 0.0,
        "syntheticRisk": 0.0,
        "signals": [],
        "qualitySignals": [],
        "features": {},
        "notice": "AI/synthetic detection is a forensic screening aid. It cannot prove that a document was generated by an AI tool from pixels alone.",
    }
    image = _load_image(file_path)
    if image is None:
        return result
    result["enabled"] = True
    result["available"] = True

    h, w = image.shape[:2]
    geometry = _token_geometry_from_ocr(ocr_text, ocr_confidence)
    texture = _block_texture(image)
    ela = _ela_signal(file_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    lap_var = float(cv2.Laplacian(gray, cv2.CV_64F).var())
    edge_density = float(np.mean(cv2.Canny(gray, 50, 150) > 0))
    text_density = min(1.0, len(str(ocr_text or "")) / max((w * h) / 9000, 1.0))
    signal_points = 0.0
    signals = []




    quality_signals = []
    sharp_text_mismatch = lap_var >= 350 and float(ocr_confidence or 0) < 58 and len(str(ocr_text or "")) >= 60
    moderate_text_mismatch = lap_var >= 260 and float(ocr_confidence or 0) < 68 and len(str(ocr_text or "")) >= 50
    if sharp_text_mismatch:
        quality_signals.append({
            "type": "TEXT_RENDERING_MISMATCH",
            "severity": "REVIEW",
            "message": "The image is reasonably sharp but OCR readability is weak; this lowers extraction confidence rather than proving manipulation.",
        })
    elif moderate_text_mismatch:
        quality_signals.append({
            "type": "TEXT_RENDERING_MISMATCH",
            "severity": "REVIEW",
            "message": "OCR readability is lower than expected for the image sharpness; field extraction should be reviewed.",
        })

    if texture["texture_outlier_ratio"] >= 0.10 and texture["noise_cv"] >= 0.75:
        signal_points += 22
        signals.append({"type": "LOCAL_TEXTURE_INCONSISTENCY", "severity": "HIGH", "message": "Several regions have markedly different texture/noise statistics from the rest of the document."})
    elif texture["texture_outlier_ratio"] >= 0.05 and texture["noise_cv"] >= 0.50:
        signal_points += 10
        signals.append({"type": "LOCAL_TEXTURE_INCONSISTENCY", "severity": "MEDIUM", "message": "Some local regions have unusual texture/noise characteristics."})




    if lap_var >= 700 and texture["texture_cv"] < 0.18 and texture["noise_cv"] < 0.28 and edge_density >= 0.035:
        signal_points += 20
        signals.append({"type": "SYNTHETIC_RENDER_UNIFORMITY", "severity": "HIGH", "message": "Image texture and noise are unusually uniform for a photographed/scanned document while edge detail remains very crisp."})
    elif lap_var >= 500 and texture["texture_cv"] < 0.25 and texture["noise_cv"] < 0.40:
        signal_points += 9
        signals.append({"type": "SYNTHETIC_RENDER_UNIFORMITY", "severity": "MEDIUM", "message": "The document has a highly uniform digital-render texture pattern."})

    if ela["ela_outlier_ratio"] >= 0.08 and ela["ela_max_z"] >= 6:
        signal_points += 20
        signals.append({"type": "ELA_OUTLIERS", "severity": "HIGH", "message": "Block-level recompression response contains strong local outliers."})
    elif ela["ela_outlier_ratio"] >= 0.04 and ela["ela_max_z"] >= 5:
        signal_points += 9
        signals.append({"type": "ELA_OUTLIERS", "severity": "MEDIUM", "message": "Some regions respond differently to recompression."})

    if geometry["token_count"] >= 10 and geometry["height_cv"] >= 0.85:
        signal_points += 13
        signals.append({"type": "TYPOGRAPHY_GEOMETRY_VARIATION", "severity": "MEDIUM", "message": "OCR text boxes show unusually high variation in rendered text height."})

    if geometry["token_count"] >= 12 and geometry["conf_std"] >= 30:
        quality_signals.append({"type": "OCR_CONFIDENCE_FRAGMENTATION", "severity": "REVIEW", "message": "Text readability varies sharply across the same document; this is an extraction-confidence signal."})



    normalized = str(id_type or "").strip().upper()
    if normalized == "COLLEGE_ID":
        required = ["name", "document_number", "course", "dob", "valid_until"]
        present = sum(bool(extracted_fields.get(k)) for k in required)
        if present <= 3:
            quality_signals.append({"type": "TEMPLATE_FIELD_GAP", "severity": "REVIEW", "message": "Some expected College ID fields were not reliably extracted."})


    score = float(max(0.0, min(100.0, signal_points)))
    if score >= 55:
        band = "HIGH"
    elif score >= 25:
        band = "MEDIUM"
    else:
        band = "LOW"

    result.update({
        "band": band,
        "score": round(score, 1),
        "aiCreatedRisk": round(score, 1),
        "syntheticRisk": round(score, 1),
        "signals": signals,
        "qualitySignals": quality_signals,
        "features": {
            "width": w,
            "height": h,
            "laplacianVariance": round(lap_var, 2),
            "edgeDensity": round(edge_density, 5),
            "ocrConfidence": round(float(ocr_confidence or 0), 2),
            "ocrTextLength": len(str(ocr_text or "")),
            "textDensity": round(text_density, 4),
            "tokenGeometry": {k: round(float(v), 3) for k, v in geometry.items()},
            "texture": {k: round(float(v), 4) for k, v in texture.items()},
            "ela": {k: round(float(v), 4) for k, v in ela.items()},
        },
    })
    return result
